version: "3.8"

services:

  nginx:
    build: ./nginx
    container_name: workflow_nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - server
    networks:
      - workflow-network

  mysql:
    image: mysql
    container_name: workflow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - workflow-network

  server:
    build: ./server
    container_name: workflow_server
    restart: always
    ports:
      - "5002:5000"
    depends_on:
      - mysql
      - minio
    environment:
      # MYSQL
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}

      # MINIO
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}

      # CORS
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    networks:
      - workflow-network

  web:
    build: ./web
    container_name: workflow_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_MINIO_ENDPOINT: ${VITE_MINIO_ENDPOINT}
      VITE_MINIO_BUCKET: ${VITE_MINIO_BUCKET}
    depends_on:
      - minio
      - server
    networks:
      - workflow-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ${MINIO_DATA_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - workflow-network

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
        mc mb --ignore-existing local/${MINIO_BUCKET} &&
        mc anonymous set public local/${MINIO_BUCKET} &&
        echo 'Bucket ready!'
      "
    networks:
      - workflow-network

networks:
  workflow-network:
    driver: bridge

volumes:
  mysql_data: